### ISSUE TITLE
setwebhook with self-signed certificate

### ISSUE THREAD

**Issue by mansarip** [depoio/node-telegram-bot#39]
Telegram new updates :
- Added support for self-signed certificates: upload your certificate using the certificate parameter in the setWebhook method.

Is there any way I can use self-signed cert? Thanks.

**Comment by shernshiou** [comment]
I will take a look.. Thanks for the update.

**Comment by hbagheri** [comment]
I have created my self-signed certificate using https://core.telegram.org/bots/self-signed. 
Then tried to upload my publick key (.pem) to telegram server using form below.
seems it do not works yet?
I have posted my  my publick key (.pem) with name 'certificate' and webhook url with name of 'url' to 'https://api.telegram.org/bot<MYTOKEN>/setWebhook'
using a normal html form
would any one please help me to solve it?
How match time it may takes to active a webhook? 
It may is because of my hurry! 


<form method='post' action="https://api.telegram.org/bot<MYTOKEN>/setWebhook" enctype="multipart/form-data">
 <b>URL:</b>
 <input name="url" type="text" />
 <b>Pem:</b>
 <input name="certificate" type="file" /> 
 <input type="submit" value="submit"/> 
 <input type="reset" value="reset"/>
 </from>

**Comment by shernshiou** [comment]
@hbagheri I have not implemented self signed cert. I am looking into supporting this feature in the future.

**Comment by shernshiou** [comment]
Merge into issue #28
